blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home_view, name='home'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.blog_post, name='blog_post'),
    path('about/', views.about, name='about'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('comment/<int:post_id>/', views.comment, name='comment'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field
from django.utils import timezone
from taggit.managers import TaggableManager
from django.urls import reverse
from django.core.mail import send_mass_mail
from django.conf import settings

class PublishedManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset() \
                                    .filter(status=Post.Status.PUBLISHED)

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250, blank=False)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    image = models.ImageField(upload_to='media/%Y/%m/%d/', blank=False)
    body = CKEditor5Field(blank=False)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self) -> str:
        return self.title    

    def get_absolute_url(self):
        return reverse('blog_post', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
    
    def save(self, *args, **kwargs):
        if self.pk and self.status == self.Status.PUBLISHED:
            emails = Email.objects.all()
            emails = emails.values_list('email', flat=True)
            messages = [
                (
                f"New Post: {self.title}",
                f"You can read the post here: localhost:8000{self.get_absolute_url()}",
                'settings.EMAIL_HOST_USER',
                emails
                )
            ]

            send_mass_mail(messages, fail_silently=True)
        return super().save(*args, **kwargs)

class Email(models.Model):
    email = models.EmailField()
    subscribed = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.email
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=150, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)    
    comment = models.TextField(blank=False, null=False)

    def __str__(self) -> str:
        return self.name

blog/forms.py
from django import forms
from .models import Email, Comment

class EmailForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = ['email']
        labels = {'email':''}
        widgets = {
            'email': forms.EmailInput(attrs={'id': 'semail', 'class': 'form-control me-md-1 semail', 'placeholder': 'Enter email'})
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'comment']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Email, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from .forms import EmailForm, CommentForm
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from django.http import JsonResponse
from django.db.models import Count

def home_view(request):
    email_form = EmailForm()
    post_list = Post.published.all()
    paginator = Paginator(post_list, 6)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)    
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)    
    
    return render(request, 'blog/index.html', {'posts':posts, 'email_form':email_form})

def blog_post(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, publish__year = year, publish__month = month, publish__day = day, slug = post)
    form = CommentForm()
    comments = Comment.objects.filter(post = post)
    tags = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=tags).exclude(id=post.id)
    similar_posts = similar_posts.annotate(count=Count('tags')).order_by('-count', '-publish')[:4]
    return render(request, 'blog/blog-post.html', {'post':post, 'form':form, 'comments':comments, 'similar_posts':similar_posts})

def about(request):
    email_form = EmailForm()
    return render(request, 'blog/about.html', {'email_form':email_form})

@require_POST
def subscribe(request):
    emails = Email.objects.all()
    emails = emails.values_list('email', flat=True)
    form = EmailForm(request.POST)
    if form.is_valid():
        email = form.cleaned_data['email']
        if email not in emails and email != settings.EMAIL_HOST_USER:
            form.save()
            send_mail('👋 Welcome to Shayxon\'s Blog!',
                        "Hey there! "
                        "Thanks for joining My Blog! I'm pumped to have you with us. Here, we're all about making coding fun and easy to understand. "
                        "Whether you're just starting out or a seasoned pro, you'll find helpful tips, cool projects, and plenty of support from our community. "
                        "Feel free to dive into our posts, ask questions, and share your own coding adventures. Let's learn and grow together! "
                        "Happy coding! "
                        "Founder, Shayxon Toirjonov"
                      , 'settings.EMAIL_HOST_USER', [email], fail_silently=True)
            messages.success(request, "You subscribed succesfully!")
        else:
            messages.error(request, "Email already exists!")
    return redirect('home')

@require_POST
def comment(request, post_id):
    form = CommentForm(request.POST)
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)

    if form.is_valid():
        if post:
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.save()

            return JsonResponse({'status':200})
    return JsonResponse({'status': 400})

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">
    <link rel="shortcut icon" href="{% static 'icon.png' %}">

    <link rel="stylesheet" href="{% static 'plugins/highlight/styles/monokai-sublime.css' %}">

    <!-- FontAwesome JS-->
    <script defer src="{% static 'fontawesome/js/all.min.js' %}"></script>

    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="{% static 'css/theme-1.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

</head>

<body>
    <header class="header text-center">
        <h1 class="blog-name pt-lg-4 mb-0"><a class="no-text-decoration" href="{% url 'home' %}">Shayxon's Blog</a></h1>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation"
                aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navigation" class="collapse navbar-collapse flex-column">
                <div class="profile-section pt-3 pt-lg-0">
                    <img class="profile-image mb-3 rounded-circle mx-auto" src="{% static 'images/profile1.jpg' %}"
                        alt="image">

                    <div class="bio mb-3">Hi, my name is Shayxon Toirjonov. Briefly introduce yourself here. You can
                        also
                        provide a link to the about page.<br><a href="{% url 'about' %}">Find out more about me</a>
                    </div>
                    <!--//bio-->
                    <ul class="social-list list-inline py-3 mx-auto">
                        <li class="list-inline-item"><a
                                href="https://www.linkedin.com/in/shayxon-toirjonov-7312792aa/"><i
                                    class="fab fa-linkedin-in fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="https://github.com/Shayxon"><i
                                    class="fab fa-github-alt fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="https://www.instagram.com/shayxon77/"><i
                                    class="fab fa-instagram fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="https://t.me/shayxon"><i
                                    class="fab fa-telegram fa-fw"></i></a></li>
                    </ul><!--//social-list-->
                    <hr>
                </div><!--//profile-section-->

                <ul class="navbar-nav flex-column text-start">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'home' %}"><i class="fas fa-home fa-fw me-2"></i>Blog
                            Home
                            <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}"><i class="fas fa-user fa-fw me-2"></i>About Me</a>
                    </li>
                </ul>

                <div class="my-2 my-md-3">
                    <a class="btn btn-primary" href="https://themes.3rdwavemedia.com/" target="_blank">Get in Touch</a>
                </div>
            </div>
        </nav>
    </header>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }}">
            {{ message|safe }}
            <a href="#" class="close">x</a>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    {% block content %}

    {% endblock %}

    <footer class="footer text-center py-2 theme-bg-dark">

        <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
        <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart"
                style="color: #fb866a;"></i> by <a href="https://themes.3rdwavemedia.com" target="_blank">Xiaoying
                Riley</a></small>

    </footer>

    <!-- Javascript -->
    <script src="{% static 'plugins/popper.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Page Specific JS -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js"></script>
    
    <!-- Custom JS -->
    <script src="{% static 'js/blog.js' %}"></script>


    <script>
        document.querySelectorAll('.close').forEach(function(closeButton) {
            closeButton.addEventListener('click', function(event) {
                event.preventDefault(); // Prevent the default link behavior
                this.parentNode.remove(); // Remove the parent <li> element when the close button is clicked
            });
        });
    
        // Automatically remove messages after 4 seconds
        setTimeout(function() {
            var messages = document.querySelectorAll('.messages li');
            messages.forEach(function(message) {
                message.remove();
            });
        }, 4000);


    </script>
</body>

</html>

blog/templates/blog/about.html
{% extends 'base.html' %}

{% block title %}
About
{% endblock %}

{% block content %}

<div class="main-wrapper">

	<article class="about-section py-5">
		<div class="container">
			<h2 class="title mb-3">About Me</h2>

			<p>Hey there, I'm Shayxon Toirjonov! Born on December 7, 2006, I've always loved playing around with
				technology. Programming caught my interest early, especially Python backend development. It's like
				solving puzzles, figuring out how to make things work behind the scenes. I'm all about exploring and
				learning new tricks to improve my coding skills. </p>
			<h5 class="mt-5">About The Blog</h5>
			<p>Whether you're a beginner or an expert, you'll find helpful tips and tricks here. I cover everything from
				building websites with HTML and CSS to creating bots for Telegram. It's all
				about making programming fun and accessible for everyone. So if you're curious about coding or want to
				learn something new, stick around! There's always something
				interesting to discover.</p>
			<h5 class="mt-5">My Skills and Experiences</h5>
			<p>I'm a Python backend developer. I specialize in building efficient systems that
				power websites and applications. I'm also familiar with HTML, CSS and JavaScript</p>
		</div>
	</article><!--//about-section-->

	<section class="cta-section theme-bg-light py-5">
		<div class="container text-center">
			<h2 class="heading">Newsletter</h2>
			<div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
			<div class="single-form-max-width pt-3 mx-auto">
				<form class="signup-form row g-2 g-lg-2 align-items-center" action="{% url 'subscribe' %}" method="post">
					<div class="col-12 col-md-9">
						{% csrf_token %}
						{{email_form.as_p}}
					</div>
					<div class="col-12 col-md-2" style="margin-top: -8px;">
						<button type="submit" class="btn btn-primary">Subscribe</button>
					</div>
				</form><!--//signup-form-->
			</div><!--//single-form-max-width-->
		</div><!--//container-->
	</section>

</div><!--//main-wrapper-->

{% endblock %}

blog/templates/blog/blog-post.html
{% extends 'base.html' %}

{% block title %}
Blog Posts
{% endblock %}

{% block content %}

<div class="main-wrapper">

	<article class="blog-post px-3 py-5 p-md-5">
		<div class="container single-col-max-width">
			<header class="blog-post-header">
				<h2 class="title mb-2">{{post.title}}</h2>
				<div class="meta mb-3"><span class="date">{{post.publish}}</span><span class="time">
						<span class="comment"><p class="text-link">{{post.comments.count}} comment{{post.comments.count|pluralize}}</p></span></div>
			</header>

			<div class="blog-post-body">
				<figure class="blog-banner">
					<a href="https://made4dev.com"><img class="img-fluid" src="/media/{{post.image}}" alt="image"></a>
				</figure>
				<p>{{post.body|safe}}</p>

			</div>

			<div class="blog-comments-section">

			</div><!--//blog-comments-section-->

		</div><!--//container-->
		<br><br>
		<div class="similar-posts">
			<h2>Similar Posts</h2>
			<ul>
				{% for post in similar_posts %}
					<li><a href="{{ post.get_absolute_url }}">{{post.title}}</a></li>
					{%empty%}
					<h4>There is no similar posts yet!</h4>
				{% endfor %}
			</ul>
		</div>
		<br><br><br>
		<h2 style="text-align: center; margin-bottom: 20px; font-size: 24px; color: #333;">Leave a Comment</h2>

		<form method="post" id="comment-form">
			{% csrf_token %}
			{{form.as_p}}
			<input type="submit" id="comment_btn" value="Submit">
		</form>
		<br>
		<div class="comment-section">
			<h2>Comments</h2>
			<br>
			<div id="comments-container">
				{% for comment in comments %}
				<div class="comment">
					<h3>{{ comment.name }}</h3>
					<p>{{ comment.comment }}</p>
				</div>
				{% endfor %}
			</div>
		</div>

	</article>

	<section class="promo-section theme-bg-light py-5 text-center">
		<div class="container">
			<!-- <h2 class="title">Promo Section Heading</h2>
			<p>You can use this section to promote your side projects etc. Lorem ipsum dolor sit amet, consectetuer
				adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. </p> -->
		</div><!--//container-->
	</section><!--//promo-section-->

</div><!--//main-wrapper-->
<script type="text/javascript">
	$(document).ready(function () {
		$('#comment_btn').click(function (e) {
			e.preventDefault();
			name = $('#id_name').val()
			comment = $('#id_comment').val(),

			$.ajax({
				type: "POST",
				url: `/comment/${'{{post.id}}'}/`,
				headers: { 'X-CSRF-TOKEN': $('meta[name="csrf_token"]').attr('content'), '_method': 'patch' },
				data: {
					name: name,
					email: $('#id_email').val(),
					comment: comment,
					csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
				},
				success: function (response) {
					if (response.status == 200){
						$('#comment-form')[0].reset();
						$('#comments-container').append(`<div class='comment'>
															<h3>${name}</h3>
															<p>${comment}</p>
														</div>`)
						let count = $('.text-link').text().split(" ")[0]
						count = parseInt(count) + 1
						if (count == 1){
							$('.text-link').text(`${count} comment`)
						} else {
							$('.text-link').text(`${count} comments`)
						}
					} else {
						alert('Fill all fields correctly!')
					}									
				}
			});
		});
	});
</script>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}
Blog
{% endblock %}

{% block content %}
<div class="main-wrapper">

	<section class="cta-section theme-bg-light py-5">
		<div class="container text-center single-col-max-width">
			<h2 class="heading">Welcome To My Blog</h2>
			<div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
			<div class="single-form-max-width pt-3 mx-auto">
				<form class="signup-form row g-2 g-lg-2 align-items-center" action="{% url 'subscribe' %}" method="post">
					<div class="col-12 col-md-9">
						{% csrf_token %}
						{{email_form.as_p}}
					</div>
					<div class="col-12 col-md-2" style="margin-top: -8px;">
						<button type="submit" class="btn btn-primary">Subscribe</button>
					</div>
				</form><!--//signup-form-->
			</div><!--//single-form-max-width-->
		</div><!--//container-->
	</section>

	<section class="blog-list px-3 py-5 p-md-5">
		<div class="container single-col-max-width">
			{% for post in posts %}
			<div class="item mb-5">
				<div class="row g-3 g-xl-0">
					<div class="col-2 col-xl-3">
						<img class="img-fluid post-thumb " src="/media/{{post.image}}" alt="image">
					</div>
					<div class="col">
						<h3 class="title mb-1"><a class="text-link" href="{{ post.get_absolute_url }}">{{post.title}}</a></h3>
						<div class="meta mb-1"><span class="date">{{post.publish}}</span>
							<span class="comment"><p class="text-link">{{post.comments.count}} comment{{post.comments.count|pluralize}}</p></span>
						</div>
						<div class="intro">{% with stripped_content=post.body|striptags %}
							{{ stripped_content|slice:":250"|safe }}
						{% endwith %}</div>
						<a class="text-link" href="{{ post.get_absolute_url }}">Read more &rarr;</a>
					</div><!--//col-->
				</div><!--//row-->
			</div><!--//item-->
			{% endfor %}

			<nav class="blog-nav nav nav-justified my-5">
				{% if posts.has_previous %}
				<a class="nav-link-prev nav-item nav-link rounded-left" href="?page={{posts.previous_page_number}}">Previous<i
						class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
				{% endif %}
				{% if posts.has_next %}
				<a class="nav-link-next nav-item nav-link rounded" href="?page={{posts.next_page_number}}">Next<i
					class="arrow-next fas fa-long-arrow-alt-right"></i></a>
				{% endif %}
			</nav>

		</div>
	</section>

</div><!--//main-wrapper-->
{% endblock %}